Add files via upload
vladmosin/Java pull request #1
Opened 2019-01-19 16:37 UTC by vladmosin

HashMap

2019-01-19 19:49 UTC, yurii-litvinov requested changes
Комментарий к коммиту не очень. В остальном очень годно, но кое-что надо поправить.

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +    /**
Лучше добавлять пустую строку между сущностью и комментарием к следующей, чтобы никто не путал, к чему относится комментарий.

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        size = 0;
Вообще, оно и так инициализируется нулём

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +     * @return Returns size of array
`Returns` JavaDoc сгенерирует сам. Я бы тут вообще `@return` не писал, потому что текст полностью повторяет общее описание метода

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        return key.hashCode() % getArraySize();
hashCode может возвращать отрицательные значения, % тоже, а код вокруг к этому морально не готов. Так что оно иногда будет падать --- на длинных строках, некоторых строках национальных алфавитов и т.д.

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        String outdatedValue = arrayOfLists[getIndex(key)].put(key, value);
Если в качестве key передадут null, будет NullReferenceException, который указывает на то, что программист о чём-то не подумал. А я бы ожидал IllegalArgumentException, который указывает на то, что о чём-то не подумал пользователь

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +     * @param value Value
Вообще, лучше не писать комментарий, если нельзя написать ничего содержательного

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/HashMap.java
> +package ru.hse;
Лучше что-нибудь более специфичное, типа ru.hse.hashtable или ru.hse.hw1

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +    private class ListElement {
На самом деле, private static class, но вам про это ещё не рассказывали вроде, так что пока ок :)

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +    private int size;
Лучше не мешать public и private

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +        head.next = head.next.next;
Стоило бы проверять, что head.next существует, и что после этого вызова не нарушим инвариант head != null. Потому что без этого инварианта тут вообще всё развалится.

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +        ListElement currentElement = head.next, previousElement = head;
Лучше каждую переменную объявлять отдельно. Тут объявление previousElement при беглом просмотре программы легко не заметить.

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +        } else {
Тут лучше без else

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +            Pair[] keyValueArray = new Pair[size];
Если тип переменной очевиден из правой части присваивания, как тут, правильнее писать var

2019-01-19 19:49 UTC, yurii-litvinov commented on HashMap/src/test/java/ru/hse/HashMapTest.java
> +        HashMap hashMap = new HashMap();
Имеет смысл использовать @BeforeEach для инициализации хеш-таблицы, а то копипаст

2019-01-19 21:10 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +    /**
Fixed

2019-01-19 21:12 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        size = 0;
Fixed

2019-01-19 21:17 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +     * @return Returns size of array
Fixed

2019-01-19 21:19 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        return key.hashCode() % getArraySize();
Fixed

2019-01-19 21:37 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +        String outdatedValue = arrayOfLists[getIndex(key)].put(key, value);
Fixed

2019-01-19 21:42 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +     * @param value Value
Fixed

2019-01-19 21:48 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/HashMap.java
> +package ru.hse;
Fixed

2019-01-19 21:48 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +    private class ListElement {
Fixed

2019-01-19 21:51 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +        ListElement currentElement = head.next, previousElement = head;
Fixed

2019-01-19 21:52 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +        } else {
Fixed

2019-01-19 21:55 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +            Pair[] keyValueArray = new Pair[size];
Fixed

2019-01-19 22:00 UTC, vladmosin commented on HashMap/src/test/java/ru/hse/HashMapTest.java
> +        HashMap hashMap = new HashMap();
Fixed

2019-01-19 22:10 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +    private int size;
Можете, пожалуйста, пояснить подробнее. Не понятно, где это мешается.

2019-01-19 22:14 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +        head.next = head.next.next;
В конструкторе листа создается вспомогательный элемент с пустым ключом и значением, на который всегда указывает head. А если head.next == null, то надо бросать исключение, но java сама бросит нормальное исключение. При попытке удалить из пустого листа NullReferenceException выглядит нормально.

2019-01-19 22:17 UTC, vladmosin commented
Можете, пожалуйста, подробнее объяснить, в чем проблема с ptivate int size.

А head никогда не равен null (подробнее написано в комментарии к замечанию).

2019-01-20 10:40 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +    private int size;
Там сначала public-конструктор, потом private-поля, потом public-методы, потом private-методы, потом снова public, потом снова private и т.д. Вообще, вот дискуссия касательно порядка членов в классе: https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions, там есть несколько полезных рекомендаций. Поскольку официальная позиция стайлгайда --- "Как хотите, но чтобы это было логично", я не настаиваю на исправлении этого замечания.

2019-01-20 10:43 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/List.java
> +        head.next = head.next.next;
Нет :) NullReferenceException указывает на ошибку программиста. IllegalArgumentException или что-то такое указывает на ошибку пользователя. Вообще никогда не стоит бросать исключения, которые бросает виртуальная машина сама (например, NullReferenceException) или приводить к такой ситуации, когда исключение будет брошено (как здесь). Как понять, Вы намеренно добиваетесь креша, или просто не подумали? Как поймать такое исключение? Ведь ловить NullReferenceException --- очень плохая практика, как раз потому, что оно, как правило, указывает на ошибку в коде, и надо дать программе упасть.

2019-01-20 10:52 UTC, yurii-litvinov requested changes

2019-01-20 10:52 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/hashtable/HashMap.java
> +        if (outdatedValue == null) {
Я бы ещё value запретил быть null и явно бы проверял на это, иначе тут может возникнуть путаница между отсутствием значения и наличием значения null.

2019-01-20 10:52 UTC, yurii-litvinov commented on HashMap/src/main/java/ru/hse/hashtable/List.java
> +        head.next = head.next.next;
Тут я всё-таки хотел бы видеть IllegalStateException

2019-01-20 10:52 UTC, yurii-litvinov commented on HashMap/src/test/java/ru/hse/hashtable/HashMapTest.java
> +        HashMap hashMap = new HashMap();
Тут бы тоже `@BeforeEach`

2019-01-20 11:06 UTC, vladmosin commented on HashMap/src/test/java/ru/hse/hashtable/HashMapTest.java
> +        HashMap hashMap = new HashMap();
Fixed

2019-01-20 11:09 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/hashtable/List.java
> +        head.next = head.next.next;
Fixed

2019-01-20 11:20 UTC, vladmosin commented on HashMap/src/main/java/ru/hse/List.java
> +    private int size;
Fixed

2019-01-20 11:25 UTC, vladmosin commented
Исправлено.

2019-01-20 14:56 UTC, yurii-litvinov approved these changes
👍

2019-01-23 13:42 UTC, merged