BST was implemented
vladmosin/Java pull request #3
Opened 2019-02-03 11:34 UTC by vladmosin

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        private Node parent;
Сами поля тоже не помешало бы снабдить nullability-аннотациями

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            } else if (resultOfComparison > 0){
А тут пробела перед `{` не хватает :)

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            }
Плохо, что hasPrevious и findPrevious несимметричны. Первый знает про isReversed, второй нет.

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        root = new Node();
Тут вполне можно было и без фиктивного корня, и не думать о нём постоянно в реализации методов. Просто разрешить root-у быть null. Правда, тогда придётся проверять на null, но это логичнее, чем проверять, а не пустой ли это корневой объект.

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        root = new Node();
Немного копипаст, лучше constructor chaining

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +                throw new IllegalArgumentException("no next element");
Тут канонично NoSuchElementException кидать. IllegalArgumentException тут может свести с ума пользователя -- IllegalArgumentException бросился,  а аргумент-то next не принимает :)

2019-02-08 12:28 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            throw new IllegalArgumentException("No elements in BST");
Это IllegalStateException скорее

2019-02-08 12:37 UTC, yurii-litvinov requested changes

2019-02-08 12:37 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +                root.right = newNode;
root слишком особенный какой-то

2019-02-08 12:37 UTC, yurii-litvinov commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    private Comparator<Integer> comparator = new Comparator<Integer>() {
`new Comparator<>`, а лучше теперь вообще заменить на лямбду

2019-02-08 12:37 UTC, yurii-litvinov commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    }
Лучше разбить такие тесты на несколько. Аж на 4, на самом деле. Чтобы если один не прошёл, было ясно, что сломалось

2019-02-08 12:37 UTC, yurii-litvinov commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    void descendingIterator() {
Вообще, не очень удачное название теста. Что descendingIterator? Что он существует, что-то делает, падает, если множество пустое, что-то ещё? По имени теста непонятно.

2019-02-08 20:42 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            } else if (resultOfComparison > 0){
Fixed

2019-02-08 20:44 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        private Node parent;
Fixed

2019-02-08 20:45 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        root = new Node();
Fixed

2019-02-08 20:46 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        root = new Node();
Fixed

2019-02-08 20:48 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +                throw new IllegalArgumentException("no next element");
Fixed

2019-02-08 20:51 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            throw new IllegalArgumentException("No elements in BST");
Fixed

2019-02-08 20:51 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +                root.right = newNode;
Fixed

2019-02-08 20:53 UTC, vladmosin commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    private Comparator<Integer> comparator = new Comparator<Integer>() {
Fixed

2019-02-08 20:55 UTC, vladmosin commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    void descendingIterator() {
Fixed

2019-02-08 21:04 UTC, vladmosin commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    }
Fixed

2019-02-08 21:13 UTC, vladmosin commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +            }
Fixed

2019-02-08 21:17 UTC, vladmosin commented
Замечания исправлены.

2019-02-09 12:51 UTC, yurii-litvinov approved these changes
Всё ок, зачтена

2019-02-09 12:51 UTC, yurii-litvinov commented on BinarySearchTree/src/main/java/com/hse/binarySearchTree/BinarySearchTree.java
> +        version++;
А потом ещё в 546 строке `version++`. Не то чтобы это что-то ломало, но выглядит странно.

2019-02-09 12:51 UTC, yurii-litvinov commented on BinarySearchTree/src/test/java/com/hse/binarySearchTree/BinarySearchTreeTest.java
> +    void descendingIterator() {
Правда? :)

2019-02-10 14:38 UTC, merged